### ISSUE TITLE
Installed the Pod yet getting an error on import

### ISSUE THREAD

**Issue by jsiddharth** [devxoul/Toaster#100]
Inserted   `pod 'Toaster', '~> 2.0'` in the Podfile

Called `pod install`

Inserted `import Toaster`

No such module `Toaster`

**Comment by devxoul** [comment]
@jsiddharth can you please share the sample project with me?

**Comment by jsiddharth** [comment]
I had to manually add the Toaster pod to `Linked Frameworks and Libraries`.

**Comment by jsiddharth** [comment]
Please mark this resolved.

Thanks
Siddharth
