### ISSUE TITLE
objective c 지원 여부

### ISSUE THREAD

**Issue by hyeongyun0916** [devxoul/Toaster#104]
objective c는 지원 안하나요?
makeText는 지원 안한다고 init을 쓰라하는데 사용법을 잘 모르겠습니다.

**Comment by devxoul** [comment]
Objective-C는 공식적으로 지원하지는 않습니다만 아래와 같이 사용할 수는 있습니다.

```objc
[[[Toast alloc] initWithText:@"Hello, world!" duration:3.5] show];
```

공식적으로 Objective-C가 지원되는 버전을 찾으신다면 [1.4.2](https://github.com/devxoul/Toaster/tree/1.4.2) 버전을 확인해주세요. 참고로 이 때에는 이름이 `JLToast`였기 때문에 `pod 'JLToast' ~> '1.4'`와 같이 사용해야 합니다.

**Comment by hyeongyun0916** [comment]
감사합니다.
initWithText: duration: 는 찾을 수 없어서
[[[Toast alloc] initWithText:@"Hello, world!" delay:.0f duration:.5f] show];
로 해결하였습니다.^^
