### ISSUE TITLE
Toaster.Toast went isFinished=YES without being started by the queue it is in

### ISSUE THREAD

**Issue by asrivastav973** [devxoul/Toaster#107]
This happens randomly in my app when switching to and fro screens which show toast after getting an api response.

**Comment by devxoul** [comment]
@asrivastav973 Hmm, could you reproduce the bug in the new project?

**Comment by asrivastav973** [comment]
I will try to reproduce this bug in a new project and then share with you.

**Comment by devxoul** [comment]
Thanks :+1:

**Comment by devxoul** [comment]
@asrivastav973, this is fixed in #109 and will be released :)

**Comment by asrivastav973** [comment]
Thanks brother 👍
