### ISSUE TITLE
is attributedText supported?

### ISSUE THREAD

**Issue by iad24** [devxoul/Toaster#114]

**Comment by devxoul** [comment]
This is not supported yet.

**Comment by vitchor** [comment]
Hi, I've made the changes to support attributedText in my local project. Let me know if you'd like me to create a PR (or fork it).

**Comment by Coeur** [comment]
@vitchor Pull Request is welcome.

**Comment by vitchor** [comment]
Done :)

**Comment by Coeur** [comment]
Done by #157. Will be available in Toaster 2.3.0. Thank you @cozzin.
