### ISSUE TITLE
Toast appears behind keyboard on iOS 11

### ISSUE THREAD

**Issue by ldiqual** [devxoul/Toaster#117]
https://drive.google.com/file/d/0Bys2UYWmcgc0T1l5cDJZcDJDejA/view

**Comment by supercartoon** [comment]
T.T

**Comment by vikasgore** [comment]
Any solution?

**Comment by Mahan3340** [comment]
Same here

**Comment by raj-zealous** [comment]
Same thing Happen .any idea ?

**Comment by raj-zealous** [comment]
same thing happing

**Comment by Mahan3340** [comment]
not yet unfortunately I'm using this lib for now till this one get fixed 
https://github.com/scalessec/Toast-Swift

**Comment by raj-zealous** [comment]
Hey, Mahan Got Solution. just  Replace the code with **ToastWindow.shared.addSubview(self.view**) to **UIApplication.shared.windows[UIApplication.shared.windows.count - 1].addSubview(self.view)** top most window.

**Comment by Mahan3340** [comment]
@raj-zealous I did so but now its not showing any toast at all :-/

**Comment by andyHa** [comment]
@raj-zealous @Mahan3340 It fixed the problem in my case - could you please update the code - or do you want me to supply a PR?

**Comment by devxoul** [comment]
Hey guys, sorry for delay. #124 is a patch for this issue. Please try and let me know if it works!

**Podfile**

```
pod 'Toaster', :git => 'https://github.com/devxoul/Toaster.git', :branch => 'ios-11-above-keyboard'
```

then

```console
$ pod install
```

**Comment by tusecani** [comment]
I have updated to ios-11-above-keyboard and have a problem
it shows toast over keyboard but it crashes when keyboard dismissed. (self.view.endEditing(true))

**Comment by devxoul** [comment]
@tusecani can you share how can I reproduce the bug?

**Comment by Mahan3340** [comment]
same here for keyboard crash ++

**Comment by devxoul** [comment]
@tusecani @Mahan3340 Thanks for reporting. I could reproduce the same bug. I'm currently look for it. I'll update a PR after finding a solution!

**Comment by Mahan3340** [comment]
@devxoul Hey, I'll appreciate that if you could fix this sooner as we are about to release a version soon  😄

**Comment by dmitry-textmagic** [comment]
@tusecani is there any update on this issue? It would be great to see some solution, the current fix does not work at 11.2 unfortunately. Thanks!

**Comment by devxoul** [comment]
I couldn't make enough spare time for this issue. Help is always welcomed.

**Comment by ciccioska** [comment]
Hi, I can open a PR for this!

**Comment by zeushin** [comment]
토스트가 사라진 이후에도 계속 key window가 ToastWindow인 상태로 남아 있는 경우가 있어 메인 window를 다시 key window로 교체한 후에 키보드가 잘 올라오는 것을 확인했습니다.
참고하여 수정해 주시면 될듯 합니다 : ]

아니면, 제가 조만간 PR을 생성해 볼게요!!

**Comment by Coeur** [comment]
After reviewing and testing everybody's solutions, I came up with a non-crashing, always working, solution: #135.

**Comment by devxoul** [comment]
Hey guys, sorry for delay. I updated the implementation of #124. I'd be really appreciate if you can test it on your app. Unfortunately my machine doesn't work with iOS 9 simulator after upgrading my mac to macOS Mojave :(

**Comment by Mahan3340** [comment]
@devxoul tested it working fine in iOS 11.4 thanks
