### ISSUE TITLE
Crash on Keyboard Dismissed 

### ISSUE THREAD

**Issue by Mahan3340** [devxoul/Toaster#125]
I show a toast when keyboard is open then when i want to dismiss the keyboard the app will crash , and the reason is setting alpha to a nil view in Toaster.swift file around line 134

**Comment by Coeur** [comment]
Your issue refers to: https://github.com/devxoul/Toaster/blob/abbc037f422b9157c5488b7671ec76fc72549224/Sources/Toast.swift#L134

But `view: ToastView` is not nullable, so I don't see how it's possible. Please provide an [MCVE](https://stackoverflow.com/help/mcve) and we'll re-open the issue.
