### ISSUE TITLE
Swift 4 generate @objc inference warning

### ISSUE THREAD

**Issue by hcstudt** [devxoul/Toaster#126]
It seems that the use of Swift 3 @objc inference in Swift 4 mode is deprecated.
I get the warning message I recieve:
The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Toaster" target.

**Comment by devxoul** [comment]
It is `Default` at this time.

<img width="660" alt="screen shot 2018-01-03 at 3 58 15 am" src="https://user-images.githubusercontent.com/931655/34495845-58af53f4-f03a-11e7-8968-dd1c434205d2.png">

How did you get that warning message?

**Comment by Coeur** [comment]
The master branch doesn't suffer from that issue anymore at this time, so I'm closing that issue.
