### ISSUE TITLE
Any plan to update to cocoapod for Swift 4.2?

### ISSUE THREAD

**Issue by shahdhiren** [devxoul/Toaster#140]

**Comment by devxoul** [comment]
[Toaster 2.2.0](https://github.com/devxoul/Toaster/releases/tag/2.2.0) supports both Swift 4.2 and 5.0 :)

**Comment by Coeur** [comment]
Support for Swift 4.2 (and Swift 5.0) is available on the master branch, so you can simply do:
```ruby
pod 'Toaster', :git => 'https://github.com/devxoul/Toaster', :branch => 'master'
```
