### ISSUE TITLE
Could not build Objective-C module 'Toaster'

### ISSUE THREAD

**Issue by anonym24** [devxoul/Toaster#143]
![image](https://user-images.githubusercontent.com/8851301/55115671-c3905c80-50ed-11e9-959e-8a0a93971b2d.png)

**Comment by anonym24** [comment]
I don't want just for this library change something in my configuration

**Comment by devxoul** [comment]
How did you install Toaster?

**Comment by Coeur** [comment]
Please show your Podfile, Podfile.lock and eventually a sample project demonstrating the problem. Also make sure you have [`use_frameworks!`](https://guides.cocoapods.org/syntax/podfile.html#use_frameworks_bang) or explain why you don't.

**Comment by Coeur** [comment]
Well, please see my previous message and we'll reopen the issue if needed.

**Comment by Fokinmc** [comment]
Hi 
I can't install Toaster
<img width="507" alt="Снимок экрана 2020-11-21 в 13 42 39" src="https://user-images.githubusercontent.com/24645267/99870697-6ec52200-2bff-11eb-9fc7-bc1414fdf0f1.png">


<img width="797" alt="Снимок экрана 2020-11-21 в 13 43 15" src="https://user-images.githubusercontent.com/24645267/99870715-843a4c00-2bff-11eb-82eb-1703e9e92018.png">

help my please

**Comment by Fokinmc** [comment]
I edit
open class ToastView: UIView {
add 
case .Mac:
in 3 places
  @objc open dynamic var bottomOffsetPortrait: CGFloat = {
  @objc open dynamic var bottomOffsetLandscape: CGFloat = {
      switch UIDevice.current.userInterfaceIdiom {
