### ISSUE TITLE
Issue with UIImagePickerController

### ISSUE THREAD

**Issue by dumpzealousys** [devxoul/Toaster#152]
We are using toaster from long time.
Now we are facing issue while working with UIImagePickerController. When we go for image picking from UIImagePickerController and after completed pickup we have to display toast message to user. When we show toast message it don't see to user but after some time when we open keyboard for UITextField, old toast messages come up on keyboard.

Please help to get out of this issue.

**Comment by Coeur** [comment]
We'll try to investigate. Note that a piece of code to reproduce the issue is even better. And testing different versions of Toaster would be nice to figure out which version/commit broke it, or if it has always been broken.

**Comment by dumpzealousys** [comment]
Version : Toaster (2.2.0)

Code to reproduce :

func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey : Any]) {

        let image = self.allowEditing ? info[UIImagePickerController.InfoKey.editedImage] as! UIImage : info[UIImagePickerController.InfoKey.originalImage] as! UIImage

        let fixedImage = UIImage(cgImage: image.cgImage!, scale: image.scale, orientation: image.imageOrientation)
        Toast(text: "Hello, Great image.").show()
        callback(fixedImage)
        
        picker.dismiss(animated: true, completion: nil)
    }
    
    func imagePickerControllerDidCancel(_ picker: UIImagePickerController) {
        picker.dismiss(animated: true) { 
            print("User cancelled")
        }
    }

**Comment by Coeur** [comment]
I can confirm the issue. I've added your code in the sample app (https://github.com/devxoul/Toaster/commit/f60746f88bbf11826701abfe6070343555b7a4c8), and now we just need to find a fix.

**Comment by dumpzealousys** [comment]
Thanks Coeur for confirming. Let me know when you fixed.

**Comment by Coeur** [comment]
@dumpzealousys please try the master branch, and I'll make a release if it works for you.
