### ISSUE TITLE
Could not build project using Toaster with CocoaPods on Xcode 11.0 beta 4 (11M374r)

### ISSUE THREAD

**Issue by minacle** [devxoul/Toaster#153]
CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'Toaster' from project 'Pods')
        cd /Users/<REDACTED>/Developer/<REDACTED>/Pods
        export DEVELOPER_DIR=/Users/<REDACTED>/Applications/Xcode-11M374r.app/Contents/Developer
        export SDKROOT=/Users/<REDACTED>/Applications/Xcode-11M374r.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk
        /Users/<REDACTED>/Applications/Xcode-11M374r.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name Toaster -Onone -enable-batch-mode -enforce-exclusivity=checked -DDEBUG -D COCOAPODS -suppress-warnings -w -Xanalyzer -analyzer-disable-all-checks -sdk /Users/<REDACTED>/Applications/Xcode-11M374r.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk -target arm64-apple-ios8.0 -g -module-cache-path /Users/<REDACTED>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -Xfrontend -serialize-debugging-options -embed-bitcode-marker -enable-testing -index-store-path /Users/<REDACTED>/Library/Developer/Xcode/DerivedData/<REDACTED>/Index/DataStore -swift-version 5 -I /Users/<REDACTED>/Library/Developer/Xcode/DerivedData/<REDACTED>/Build/Products/Debug-iphoneos/Toaster -F /Users/<REDACTED>/Library/Developer/Xcode/DerivedData/<REDACTED>/Build/Products/Debug-iphoneos/Toaster -c -j4 /Users/<REDACTED>/Developer/<REDACTED>/Pods/Toaster/Sources/Toast.swift /Users/<REDACTED>/Developer/<REDACTED>/Pods/Toaster/Sources/ToastCenter.swift /Users/<REDACTED>/Developer/<REDACTED>/Pods/Toaster/Sources/ToastView.swift /Users/<REDACTED>/Developer/<REDACTED>/Pods/Toaster/Sources/ToastWindow.swift -output-file-map /Users/<REDACTED>/Library/Developer/Xcode/DerivedData/<REDACTED>/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Toaster.build/Objects-normal/arm64/Toaster-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/<REDACTED>/Library/Developer/Xcode/DerivedData/<REDACTED>/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Toaster.build/Objects-normal/arm64/Toaster.swiftmodule -Xcc -I/Users/<REDACTED>/Library/Developer/Xcode/DerivedData/<REDACTED>/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Toaster.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/<REDACTED>/Library/Developer/Xcode/DerivedData/<REDACTED>/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Toaster.build/Toaster-generated-files.hmap -Xcc -I/Users/<REDACTED>/Library/Developer/Xcode/DerivedData/<REDACTED>/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Toaster.build/Toaster-own-target-headers.hmap -Xcc -I/Users/<REDACTED>/Library/Developer/Xcode/DerivedData/<REDACTED>/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Toaster.build/Toaster-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/<REDACTED>/Library/Developer/Xcode/DerivedData/<REDACTED>/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Toaster.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/<REDACTED>/Library/Developer/Xcode/DerivedData/<REDACTED>/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Toaster.build/Toaster-project-headers.hmap -Xcc -I/Users/<REDACTED>/Library/Developer/Xcode/DerivedData/<REDACTED>/Build/Products/Debug-iphoneos/Toaster/include -Xcc -I/Users/<REDACTED>/Library/Developer/Xcode/DerivedData/<REDACTED>/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Toaster.build/DerivedSources-normal/arm64 -Xcc -I/Users/<REDACTED>/Library/Developer/Xcode/DerivedData/<REDACTED>/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Toaster.build/DerivedSources/arm64 -Xcc -I/Users/<REDACTED>/Library/Developer/Xcode/DerivedData/<REDACTED>/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Toaster.build/DerivedSources -Xcc -DPOD_CONFIGURATION_DEBUG=1 -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -emit-objc-header -emit-objc-header-path /Users/<REDACTED>/Library/Developer/Xcode/DerivedData/<REDACTED>/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Toaster.build/Objects-normal/arm64/Toaster-Swift.h -import-underlying-module -Xcc -ivfsoverlay -Xcc /Users/<REDACTED>/Library/Developer/Xcode/DerivedData/<REDACTED>/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Toaster.build/unextended-module-overlay.yaml -working-directory /Users/<REDACTED>/Developer/<REDACTED>/Pods

    <unknown>:0: error: unknown argument: '-w'
    <unknown>:0: error: unknown argument: '-Xanalyzer'
    <unknown>:0: error: unknown argument: '-analyzer-disable-all-checks'
    Command CompileSwiftSources failed with a nonzero exit code

**Comment by Coeur** [comment]
This is a CocoaPods 1.7.4 issue, not a Toaster issue.
Please update to CocoaPods 1.7.5 that was recently released for compatibility with Xcode 11 beta 4.
