### ISSUE TITLE
Toast is invisible after presenting UIActivityViewController

### ISSUE THREAD

**Issue by cozzin** [devxoul/Toaster#154]
Hi, I tested it on develop branch.
After presenting a UIActivityViewController, a UIRemoteKeyboardWindow is created.
If you put the view on this window, it is invisible.
I don't know why the UIRemoteKeyboardWindow is created. 

The current develop branch includes a feature that adds a view to the top-level window to avoid being hidden on the keyboard. So the Toast is not visible after the UIActivityViewController is presented.

![c9c56700-a89d-11e9-9e51-7a8e0e0c8e2e](https://user-images.githubusercontent.com/11647461/61846250-5cd75000-aee1-11e9-9416-11550c343d2e.png)

**Comment by Coeur** [comment]
Likely similar to #152

**Comment by cozzin** [comment]
#155 This PR solves the issue.
