### ISSUE TITLE
Status bar style is changed after ToastWindow appear.

### ISSUE THREAD

**Issue by cozzin** [devxoul/Toaster#166]
I want to set status bar style as `.lightContent` in ViewController, but after showing Toast status bar style is changed to `.default`.

I think we should return `rootViewController` in `ToastWindow`.
Is there anyone who can explain about `isShowing` property? 

```swift
  override open var rootViewController: UIViewController? {
    get {
//      guard !self.isShowing else { return nil }
      guard !self.isStatusBarOrientationChanging else { return nil }
      guard let firstWindow = UIApplication.shared.delegate?.window else { return nil }
      return firstWindow is ToastWindow ? nil : firstWindow?.rootViewController
    }
    set { /* Do nothing */ }
  }
```

**Comment by cozzin** [comment]
Oh, I found this PR https://github.com/devxoul/Toaster/pull/150.

**Comment by Coeur** [comment]
Yes, `isShowing` is a workaround for iOS 13 warnings regarding the UIWindow.rootViewController stack.

When I made #150, I attempted to preserve the statusbar style.

The current implementation is:
https://github.com/devxoul/Toaster/blob/fae2df311c768e87492f71610d77bfe6d98b2cc8/Sources/ToastWindow.swift#L43-L51

Are you having the statusbar issue with this code?

**Comment by cozzin** [comment]
@Coeur Yes, I am struggling to solve status bar issue.

1. set status bar style in view controller
```swift
final class RootViewController: UIViewController {
  override var preferredStatusBarStyle: UIStatusBarStyle {
    return .lightContent
  }
}
```

2. Show toast
```swift
Toast(text: "Basic Toast").show()
```

3. Status bar style did change to `default`
