### ISSUE TITLE
Would you like to support SPM?

### ISSUE THREAD

**Issue by shawnclovie** [devxoul/Toaster#179]
Since Xcode 11, we can use Swift Package Manager to manage most dependence for pure swift framework.

**Comment by devxoul** [comment]
Of course, I am a big fan of Swift Package Manager. I will support SPM when I have a spare time. Thanks!

**Comment by sauravm97** [comment]
Any updates on this? Is it possible to merge #181, perhaps?

**Comment by Coeur** [comment]
While I don't work on the project anymore, I merged this popular change.
