### ISSUE TITLE
Scroll to top using status bar does not work in iOS 13

### ISSUE THREAD

**Issue by cozzin** [devxoul/Toaster#180]
![ScrollToTopIssue](https://user-images.githubusercontent.com/11647461/65577030-00aaae00-dfae-11e9-900e-7bfec7a2d26c.gif)

You can test on https://github.com/cozzin/Toaster/tree/feature/scrollToTopIssue

**Comment by xissy** [comment]
Struggling with the same issue.

**Comment by cozzin** [comment]
This issue is resolved in iOS 13.2
