### ISSUE TITLE
Cannot build on Xcode 12

### ISSUE THREAD

**Issue by trevinwisaksana** [devxoul/Toaster#193]
Toaster version 2.2.0 cannot be built on Xcode 12 because there are several switch statements that are not exhausted. 

<img width="1113" alt="Screenshot 2020-06-24 at 09 15 13" src="https://user-images.githubusercontent.com/20000813/85490051-42c75580-b5fb-11ea-8ca5-426448ade254.png">

**Comment by valeriy-kolodiy** [comment]
@trevinwisaksana These errors seem to be fixed in master. So until release, you can use master version.
(e.g. with Cocoa Pods you can add dependency as `pod 'Toaster', :git => 'https://github.com/devxoul/Toaster.git', :branch => 'master'`)

**Comment by aryamansharda** [comment]
Any ETA for a new release cut? Happy to use the master version in the meantime, just curious.

**Comment by Coeur** [comment]
A new version would need to be released by devxoul himself.

**Comment by Coeur** [comment]
Closing this issue, since it's resolved on master branch.
And published as of Toaster 2.3.0 in December 2020.
