### ISSUE TITLE
please add tag 2.3.0

### ISSUE THREAD

**Issue by chrisyu-chn** [devxoul/Toaster#194]
please add tag 2.3.0 for cocoapods (Toaster (~> 2.3))

**Comment by wudijimao** [comment]
please~

**Comment by MrSkwiggs** [comment]
Yep, been waiting for this for a while... There's no SPM support either. @Coeur As-tu abandonné ce projet ? :/

**Comment by roddi** [comment]
+1 please!

**Comment by ThomWee** [comment]
Would be awesome getting an official release!

**Comment by debaj** [comment]
+1

**Comment by snakeland** [comment]
+1

**Comment by wangmingjob** [comment]
please! +1

**Comment by JimmieWong** [comment]
equals to 2.3.0
 pod 'Toaster', :git => 'git@github.com:devxoul/Toaster.git', :commit => 'aec54fc48d3d36279424103de0784c23862d19df'

**Comment by dagad** [comment]
please +1 
still waiting

**Comment by okiookio** [comment]
pull source and add to local git

**Comment by matzino** [comment]
+1

**Comment by kajz3reczka** [comment]
+1

**Comment by willbin** [comment]
+1

**Comment by codev-kuk** [comment]
+1
