### ISSUE TITLE
Switchcase must be Exhaustive

### ISSUE THREAD

**Issue by jmagi98** [devxoul/Toaster#195]
Have an issue building my project all of the sudden after an Xcode update. Traces back to this library. Says that there must be an exhaustive switch case in the ToastView file. Any way around this?

**Comment by asujiman** [comment]
<img width="863" alt="Screen Shot 2020-09-18 at 14 40 18" src="https://user-images.githubusercontent.com/10322533/93570238-e6d35980-f9bc-11ea-8ded-dfb479c50592.png">

Yeah I found this issue too. Any solution?

**Comment by mircobabini** [comment]
#196 solves this

**Comment by Coeur** [comment]
PR merged, so I'm closing this issue. But I'm not going to make a release, so you'll have to ping @devxoul and make sure to point to the "master" or "main" branches in the mean time.
