### ISSUE TITLE
Switch must be exhaustive | Version 12.0.1 (12A7300)

### ISSUE THREAD

**Issue by denishgcirklestudio** [devxoul/Toaster#201]
I have updated Xcode for iOS version 14 and when build my project it threw me this error

**Switch must be exhaustive
Do you want to add missing cases?**

When I pressed the FIX button that added the below-mentioned code. It has the same error in 4-5 places. Please check and update.

```
case .mac:
    <#code#>
@unknown default:
    <#code#>
```

![Excat issue](https://user-images.githubusercontent.com/59468606/96408974-2e3e4700-1202-11eb-98f7-c6efae9ab81f.png)

![When clicked on auto fix](https://user-images.githubusercontent.com/59468606/96408872-018a2f80-1202-11eb-878a-6be408228834.png)

**Comment by alexgarciaju** [comment]
Same issue here!

**Comment by Coeur** [comment]
Just update your pod to latest commit. See #196
