### ISSUE TITLE
Xcode 13.3.1: no Package.swift manifest for version 2.3.0

### ISSUE THREAD

**Issue by gezamiklo** [devxoul/Toaster#212]
Did add package using repo url and version up to next major. When trying to build the project, an error occurs
Showing All Messages
/Package.swift has no Package.swift manifest for version 2.3.0 in https://github.com/devxoul/Toaster

**Comment by Coeur** [comment]
Please make a pull request.
Also, pinging @achernoprudov @kuldeeptyagics2 @mcblooder in case you might want to help.

**Comment by Coeur** [comment]
Please make a pull request.
Also, pinging @achernoprudov @kuldeeptyagics2 @mcblooder in case you might want to help.

**Comment by mcblooder** [comment]
@gezamiklo 
Can you check if this fixes it for you?
[pull request](https://github.com/devxoul/Toaster/pull/213)

**Comment by gezamiklo** [comment]
Yes it does solve the problem. Did not even think this one commented line could be the problem.

**Comment by mcblooder** [comment]
> Yes it does solve the problem. Did not even think this one commented line could be the problem.

Yeah, it took me a few tries to figure it out too! Oh, Xcode

**Comment by Coeur** [comment]
Thanks
