### ISSUE TITLE
Cant install Toaster for Swift 3

### ISSUE THREAD

**Issue by ivanruizscm** [devxoul/Toaster#90]
ivan.ruiz$ pod install
Analyzing dependencies
Pre-downloading: `Toaster` from `https://github.com/devxoul/JLToast.git`
[!] Unable to find a specification for 'Toaster'.

    pod 'Toaster'

**Comment by ivanruizscm** [comment]
if i add the git source:
    pod 'Toaster', :git => 'https://github.com/devxoul/Toaster.git'
I get:
AFE0806015:ios-if--app-next-visit ivan.ruiz$ pod install
Analyzing dependencies
Pre-downloading: `Toaster` from `https://github.com/devxoul/Toaster.git`
Username for 'https://github.com':

**Comment by awclives** [comment]
Same issue here.

**Comment by devxoul** [comment]
I just uploaded 'Toaster' to CocoaPods. Please try again with **`Podfile`**:

```ruby
pod 'Toaster', '~> 2.0'
```

**Comment by awclives** [comment]
great, thanks!  love the Toaster.
