### ISSUE TITLE
Keyboard no response when toaster show

### ISSUE THREAD

**Issue by isaced** [devxoul/Toaster#94]
`ToastWindow` Will become `keyWindow`, resulting in the keyboard does not respond

**Comment by kirayamato1989** [comment]
when begin editing an UITextField then call the toast.show() may case the UITextField can't input next time

**Comment by devxoul** [comment]
@isaced, how can I reproduce the bug?

**Comment by isaced** [comment]
For the time being I can not find a way to reproduce, but in my other project, there is always the same problem, the same code put in a new empty project and no problem.

I use both PKHUD and Toaster

```
import Toaster
import PKHUD
```

```
let vc = UIViewController()
vc.view.backgroundColor = .white

self.navigationController?.pushViewController(vc, animated: true)

// show hud
HUD.flash(.systemActivity)
DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
    // show toast
    let toast = Toast(text: "Hello")
    toast.show()
    
    HUD.hide()
}
```

So, close this issue for the time being
