### ISSUE TITLE
offset when using tab bar

### ISSUE THREAD

**Issue by jmbello** [devxoul/Toaster#96]
Where can I customize toast position? this will be helpful when using tab bars, because toast shows over tab bar. Thanks

**Comment by devxoul** [comment]
Of cource. You can see `bottomOffsetPortrait` and `bottomOffsetLandscape` from https://github.com/devxoul/Toaster#appearance

**Comment by jmbello** [comment]
Oh, thanks, can't believe I didn't understand at first
